# Generated by Django 6.0.2 on 2026-04-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='retrieved_chunk_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='similarity_scores',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
