# Generated by Django 6.0.2 on 2026-07-18 19:12

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_rename_document_agent_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemanticCacheEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('query_embedding', pgvector.django.vector.VectorField(dimensions=768)),
                ('response', models.JSONField()),
                ('knowledge_version', models.CharField(db_index=True, max_length=64)),
                ('embedding_model', models.CharField(max_length=128)),
                ('hit_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_hit_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cache_entries', to='agent.agent')),
            ],
            options={
                'indexes': [models.Index(fields=['agent'], name='sem_cache_agent_idx'), pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['query_embedding'], m=16, name='sem_cache_emb_hnsw_idx', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
