# Generated by Django 6.0.2 on 2026-04-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_accessible_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='meta_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
