# Generated by Django 6.0.2 on 2026-07-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_meta_data'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='documentchunk',
            name='documents_d_documen_083a67_idx',
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document', 'embedding'], name='document_embedding_idx'),
        ),
    ]
