# Generated by Django 6.0.2 on 2026-07-18 11:58

import pgvector.django.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_remove_documentchunk_documents_d_documen_083a67_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='documentchunk',
            name='document_embedding_idx',
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document'], name='document_chunk_document_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='doc_chunk_emb_hnsw_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
